Implemented import db option
- Updated usage text to not exceed 80 characters in width (for standard terminal size)
- Updated usage text for import
- Added error message for invalid input file
- Implemented import db function
- Updated getopts opt string
- Added import parsing option

diff --git a/meditate b/meditate
--- a/meditate
+++ b/meditate
@@ -19,11 +19,17 @@ usage="Usage: ./$(basename $0) [OPTIONS]
 Options:
  -h                     this help
  -p <player>            vlc, mpv, ffplay, termux
- -t <seconds>           set meditation timer (default: infinite) (NOT IMPLEMENTED YET)
- -c <pattern>           breath pattern as a in-hold-out-hold sequence (e.g. 7070, 4444, 4662, 10_5_10_5)
-                        or as a in-out sequence (e.g. 77, 44, 46, 10_5)
- -d <file>              sqlite db file (default: "$DEFAULTDB" in the same directory)
+ -t <seconds>           set meditation timer (default: infinite)
+                        (NOT IMPLEMENTED YET)
+ -c <pattern>           breath pattern as a in-hold-out-hold sequence
+                        (e.g. 7070, 4444, 4662, 10_5_10_5) or as an
+                        in-out sequence (e.g. 77, 44, 46, 10_5)
+ -d <file>              sqlite db file (default: "$DEFAULTDB" in the
+                        same directory)
  -s [file]              show session details in the database
+ -i <importfile>        export sql or csv into database (merging of databases
+                        not supported; imported database replaces existing,
+                        if any, but backup of existing db is made)
  -e <outputfile>        export database as sql or csv, based on extension"
 
 illegal_option_error_msg() { echo "Illegal usage. Try $(basename $0) -h for usage."; }
@@ -36,6 +42,7 @@ schema_cannot_check_msg() { echo "Not checking schema, as sqldiff is not availab
 db_update_success_msg() { echo "DB updated."; }
 invalid_sequence_error_msg() { echo "Invalid sequence pattern. Try with 46 or 4444 or 10_5, or see help for usage."; }
 invalid_output_filename_error_msg() { echo "Invalid output file to export. Mention a proper filename with either csv or sql extension."; }
+invalid_input_file_error_msg() { echo "Invalid input file to import from."; }
 
 setup_db() {
   CREATETABLESTMT='CREATE TABLE IF NOT EXISTS "meditated" (
@@ -77,13 +84,43 @@ export_db() {
       sqlite3 "$DBFILE" ".dump" > "$FILENAME"
     elif [[ "$FILENAME" == *".csv" ]];
     then
-       sqlite3 -header -csv "$DBFILE" 'select * from meditated;'
+      sqlite3 -header -csv "$DBFILE" 'select * from meditated;'
     else
       invalid_output_filename_error_msg
     fi
   else
     dbfile_not_found_error_msg "<unknown>"
   fi
+}
+
+import_db() {
+  FILENAME="$1"
+  if [[ -n "$DBFILE" ]];
+  then
+    if [[ "$FILENAME" == *".sql" ]];
+    then
+      cp "$DBFILE" "$DBFILE.$(date +%Y-%m-%d-%H-%M-%S)_backup"
+      rm "$DBFILE"
+      sqlite3 "$DBFILE" < "$FILENAME"
+    elif [[ "$FILENAME" == *".csv" ]];
+    then
+      cp "$DBFILE" "$DBFILE.$(date +%Y-%m-%d-%H-%M-%S)_backup"
+      echo -e "delete from meditated;\n.mode csv\n.import $FILENAME meditated" > import.sql
+      sqlite3 "$DBFILE" < import.sql >&- 2>&-
+      if [[ "$?" -ne 0 ]];
+      then
+        tail -n +2 "$FILENAME" > "$FILENAME.noheaders"
+        echo -e "delete from meditated;\n.mode csv\n.import $FILENAME.noheaders meditated" > import.sql
+        sqlite3 "$DBFILE" < import.sql >&- 2>&-
+      fi
+    else
+      invalid_input_file_error_msg
+    fi
+  else
+    dbfile_not_found_error_msg "<unknown>"
+  fi
+
+  rm "$FILENAME".noheaders import.sql 2>&- >&-
 }
 
 check_db_schema() {
@@ -116,7 +153,7 @@ EXHALETIME=7
 EXHALEHOLDTIME=3
 
 function parse_options() {
-  while getopts ":hp:t:d:s:c:e:" opt; do
+  while getopts ":hp:t:d:s:c:e:i:" opt; do
     case "${opt}" in
       h)
         echo "$usage"
@@ -229,6 +266,11 @@ function parse_options() {
       e)
         FILENAME="$OPTARG"
         export_db "$FILENAME"
+        exit 0
+        ;;
+      i)
+        FILENAME="$OPTARG"
+        import_db "$FILENAME"
         exit 0
         ;;
       :)
